version: "3.4"
services:
  op-geth:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101105.3
    restart: unless-stopped
    stop_grace_period: 5m
    entrypoint: /scripts/start-op-geth.sh
    env_file:
      - ./envs/${NETWORK_NAME}/op-geth.env
      - .env
    volumes:
      - ./scripts/:/scripts
      - ./op_geth:/shared
      - ./op_geth:/geth
    ports:
      - 127.0.0.1:42045:8545 # rpc
      - ${PORT__OP_GETH_WS:-9994}:8546
    profiles:
      - current

  op-node:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.1.0
    restart: unless-stopped
    stop_grace_period: 5m
    entrypoint: /scripts/start-op-node.sh
    env_file:
      - .env
    volumes:
      - ./scripts/:/scripts
      - ./op_geth:/shared
    ports:
      - ${PORT__OP_NODE_P2P:-9003}:9003/udp
      - ${PORT__OP_NODE_P2P:-9003}:9003/tcp
    profiles:
      - current

  bedrock-init:
    build:
      context: ./docker/dockerfiles
      dockerfile: Dockerfile.bedrock-init
    entrypoint: /scripts/init-bedrock.sh
    env_file:
      - .env
    volumes:
      - ./scripts/:/scripts
      - ./op_geth:/shared
      - ./op_geth:/geth
      - torrent_downloads:/downloads
    profiles:
      - current


volumes:
  torrent_downloads:
